# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: Apache-2.0
---
name: 'Use Dependabot auto approvals.'

on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  ci:
    uses: goschtalt/.github/.github/workflows/approve-dependabot.yml@main
    secrets: inherit
