# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: Apache-2.0
---
name: 'CI Verification'

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'testing/**'
    tags:
      - 'v*'

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      working-directory: testing
    secrets: inherit
